import { Noto_Sans_KR } from 'next/font/google';

import type { Metadata } from 'next';
import './styles/globals.scss';

export const metadata: Metadata = {
  title: 'Weing Test',
  description: 'Generated by create next app',
};

const font = Noto_Sans_KR({
  weight: ['300', '400', '500', '700', '800'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={font.className}>{children}</body>
    </html>
  );
}
